### ISSUE TITLE
python train_segmentation.py -c ./dataloader/yaml_data/buid_endtoend_R50.yml has a error

### ISSUE THREAD

**Issue by buzhidaozenmeqimingzi** [duyhominhnguyen/LVM-Med#19]
Error shows below:
INFO: Using device cuda:5
------------
Using pre-trained models from lvm-med-resnet
Traceback (most recent call last):
  File "train_segmentation.py", line 14, in <module>
    train_2d_R50(yml_args, cfg)
  File "/root/autodl-tmp/LVM-Med/segmentation_2d/train_R50_seg_adam_optimizer_2d.py", line 224, in train_2d_R50
    net = smp.Unet(encoder_name="resnet50", encoder_weights=cfg.base.original_checkpoint, 
  File "/root/miniconda3/envs/lvm_med/lib/python3.8/site-packages/segmentation_models_pytorch/unet/model.py", line 59, in __init__
    self.encoder = get_encoder(
  File "/root/miniconda3/envs/lvm_med/lib/python3.8/site-packages/segmentation_models_pytorch/encoders/__init__.py", line 38, in get_encoder
    settings = encoders[name]["pretrained_settings"][weights]
KeyError: 'lvm-med-resnet

**Comment by buzhidaozenmeqimingzi** [comment]
Hello!I had come across a problem as above.I don't know whether it related to source code or not.Please inform me why it happened, I'll be appreciated.
